# Thousands Minigames
# Instances_Deploy_Pipeline 配置
# 相对路径相对于本 TOML 文件所在目录解析。

# 压缩包所在目录。目录路径。
archive_dir = "..\\..\\_worlds_archives\\"

# 世界根目录。目录路径。
world_dir = "..\\..\\worlds\\"

# 实例配置根目录。目录路径。
configs_root = "..\\..\\configs\\"

# 模板配置根目录。目录路径。
template_root = "..\\TM_Example_Configs\\configs\\"

# 启动脚本输出目录。目录路径。
output_dir = "..\\..\\_startup_scripts_legacy\\"

# 版本映射文件。文件路径。
version_map = ".\\Version_Map.toml"
