accepts-transfers=true
allow-flight=true
allow-nether=false
enable-command-block=true
enforce-secure-profile=false
gamemode=2
gamemode=adventure
max-players=100
motd=Thousands Minigames
online-mode=false
simulation-distance=8
spawn-protection=0
view-distance=16
